version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    container_name: mern-database
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
