version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    container_name: mern-db-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: $ROOT_USER
      MONGO_INITDB_ROOT_PASSWORD: $ROOT_PASSWORD
      ROOT_PORT: $ROOT_PORT
      MERN_APP_DB_USER: $DB_USER
      MERN_APP_DB_PASSWORD: $DB_PASSWORD
      MERN_APP_DB_NAME: $DB_NAME
    ports:
      - $ROOT_PORT:27017
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
